### ISSUE TITLE
Database layer fails on Raspberry PI 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1038]
The exception is following, and for some reason fallback to pure-Java LevelDB implementation does not happen: 

java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni32-3.2.0 in java.library.path, no leveldbjni-3.2.0 in java.library.path, no leveldbjni in java.library.path, /tmp/libleveldbjni-32-3-15379215246784981866.2: /tmp/libleveldbjni-32-3-15379215246784981866.2: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at scorex.db.LDBFactory$.loadFactory(LDBFactory.scala:136)
	at scorex.db.LDBFactory$.$anonfun$factory$1(LDBFactory.scala:121)
	at scala.collection.TraversableViewLike$FlatMapped.$anonfun$foreach$3$adapted(TraversableViewLike.scala:193)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
	at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:40)
	at scala.collection.TraversableViewLike$FlatMapped.foreach(TraversableViewLike.scala:192)
	at scala.collection.TraversableViewLike$FlatMapped.foreach$(TraversableViewLike.scala:191)
	at scala.collection.SeqViewLike$$anon$5.foreach(SeqViewLike.scala:200)
	at scala.collection.TraversableViewLike$Transformed.headOption(TraversableViewLike.scala:113)
	at scala.collection.TraversableViewLike$Transformed.headOption$(TraversableViewLike.scala:112)
	at scala.collection.SeqViewLike$AbstractTransformed.headOption(SeqViewLike.scala:40)
	at scorex.db.LDBFactory$.factory$lzycompute(LDBFactory.scala:124)
	at scorex.db.LDBFactory$.factory(LDBFactory.scala:115)
	at scorex.db.LDBVersionedStore.createDB(LDBVersionedStore.scala:42)
	at scorex.db.LDBVersionedStore.<init>(LDBVersionedStore.scala:28)
	at org.ergoplatform.nodeView.state.UtxoState$.fromBoxHolder(UtxoState.scala:202)
	at org.ergoplatform.nodeView.state.ErgoState$.generateGenesisUtxoState(ErgoState.scala:196)
	at org.ergoplatform.nodeView.state.ErgoState$.readOrGenerate(ErgoState.scala:219)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.recreatedState(ErgoNodeViewHolder.scala:126)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.genesisState(ErgoNodeViewHolder.scala:89)
	at scorex.core.NodeViewHolder.$anonfun$nodeView$1(NodeViewHolder.scala:62)
	at scala.Option.getOrElse(Option.scala:189)
	at scorex.core.NodeViewHolder.$init$(NodeViewHolder.scala:62)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:26)
	at org.ergoplatform.nodeView.UtxoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:221)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at akka.util.Reflect$.instantiate(Reflect.scala:68)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:648)
	at akka.actor.ActorCell.create(ActorCell.scala:674)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
13:51:12.081 WARN  [ctor.default-dispatcher-3] scorex.db.LDBFactory$ - Failed to load database factory org.iq80.leveldb.impl.Iq80DBFactory due to: {}
java.lang.ClassNotFoundException: org.iq80.leveldb.impl.Iq80DBFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at scorex.db.LDBFactory$.loadFactory(LDBFactory.scala:136)
	at scorex.db.LDBFactory$.$anonfun$factory$1(LDBFactory.scala:121)
	at scala.collection.TraversableViewLike$FlatMapped.$anonfun$foreach$3$adapted(TraversableViewLike.scala:193)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
	at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:40)
	at scala.collection.TraversableViewLike$FlatMapped.foreach(TraversableViewLike.scala:192)
	at scala.collection.TraversableViewLike$FlatMapped.foreach$(TraversableViewLike.scala:191)
	at scala.collection.SeqViewLike$$anon$5.foreach(SeqViewLike.scala:200)
	at scala.collection.TraversableViewLike$Transformed.headOption(TraversableViewLike.scala:113)
	at scala.collection.TraversableViewLike$Transformed.headOption$(TraversableViewLike.scala:112)
	at scala.collection.SeqViewLike$AbstractTransformed.headOption(SeqViewLike.scala:40)
	at scorex.db.LDBFactory$.factory$lzycompute(LDBFactory.scala:124)
	at scorex.db.LDBFactory$.factory(LDBFactory.scala:115)
	at scorex.db.LDBVersionedStore.createDB(LDBVersionedStore.scala:42)
	at scorex.db.LDBVersionedStore.<init>(LDBVersionedStore.scala:28)
	at org.ergoplatform.nodeView.state.UtxoState$.fromBoxHolder(UtxoState.scala:202)
	at org.ergoplatform.nodeView.state.ErgoState$.generateGenesisUtxoState(ErgoState.scala:196)
	at org.ergoplatform.nodeView.state.ErgoState$.readOrGenerate(ErgoState.scala:219)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.recreatedState(ErgoNodeViewHolder.scala:126)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.genesisState(ErgoNodeViewHolder.scala:89)
	at scorex.core.NodeViewHolder.$anonfun$nodeView$1(NodeViewHolder.scala:62)
	at scala.Option.getOrElse(Option.scala:189)
	at scorex.core.NodeViewHolder.$init$(NodeViewHolder.scala:62)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:26)
	at org.ergoplatform.nodeView.UtxoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:221)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at akka.util.Reflect$.instantiate(Reflect.scala:68)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:648)
	at akka.actor.ActorCell.create(ActorCell.scala:674)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kushti** [comment]
Strangely there's no fallback to pure-Java LevelDB version in case of such exception.

**Comment by kushti** [comment]
Fixed in #1044
