### ISSUE TITLE
Compilation failure: Cannot resolve companion instance for s493 -> IntPlusMonoidCtor(s18)

### ISSUE THREAD

**Issue by jasondavies** [ergoplatform/ergo#1095]
```
{
  val createdPreviousBlock = {(b: Box) => b.creationInfo._1 < 100}
  val createdCurrentBlock = {(b: Box) => b.creationInfo._1 == 100}

  createdPreviousBlock(SELF) && OUTPUTS.exists(createdCurrentBlock)
}
```

Strangely, changing the order of the last line makes the error go away.

```
scalan.Base$StagingException: Error in Evaluation.compile.evaluate(s499 -> ThunkForce(s474))
	at scalan.Base.$bang$bang$bang(Base.scala:36)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:876)
	at sigmastate.eval.Evaluation.$anonfun$compile$5(Evaluation.scala:759)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$4(Evaluation.scala:758)
	at sigmastate.eval.Evaluation.$anonfun$compile$8(Evaluation.scala:889)
	at sigmastate.eval.IRContext.$anonfun$checkCostWithContext$1(IRContext.scala:132)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.eval.IRContext.checkCostWithContext(IRContext.scala:129)
	at sigmastate.eval.IRContext.checkCostWithContext$(IRContext.scala:128)
	at sigmastate.eval.RuntimeIRContext.checkCostWithContext(IRContext.scala:150)
	at sigmastate.interpreter.Interpreter.$anonfun$reduceToCrypto$3(Interpreter.scala:155)
	at org.ergoplatform.validation.ValidationRules$.trySoftForkable(ValidationRules.scala:354)
	at sigmastate.interpreter.Interpreter.$anonfun$reduceToCrypto$1(Interpreter.scala:147)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.interpreter.Interpreter.reduceToCrypto(Interpreter.scala:142)
	at sigmastate.interpreter.Interpreter.reduceToCrypto$(Interpreter.scala:142)
	at org.ergoplatform.ErgoLikeInterpreter.reduceToCrypto(ErgoLikeInterpreter.scala:10)
	at sigmastate.interpreter.Interpreter.reduceToCrypto(Interpreter.scala:169)
	at sigmastate.interpreter.Interpreter.reduceToCrypto$(Interpreter.scala:168)
	at org.ergoplatform.ErgoLikeInterpreter.reduceToCrypto(ErgoLikeInterpreter.scala:10)
	at org.ergoplatform.http.api.ScriptApiRoute.$anonfun$executeWithContextR$3(ScriptApiRoute.scala:162)
	at scala.util.Success.fold(Try.scala:271)
	at org.ergoplatform.http.api.ScriptApiRoute.$anonfun$executeWithContextR$1(ScriptApiRoute.scala:158)
	at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:213)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:213)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:45)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$4(BasicDirectives.scala:407)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: scalan.Base$StagingException: Error in Evaluation.compile.evaluate(s493 -> IntPlusMonoidCtor(s18))
	at scalan.Base.$bang$bang$bang(Base.scala:36)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:876)
	at sigmastate.eval.Evaluation.$anonfun$compile$7(Evaluation.scala:774)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$6(Evaluation.scala:773)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:784)
	... 60 more
Caused by: scalan.Base$StagingException: Cannot resolve companion instance for s493 -> IntPlusMonoidCtor(s18)
	at scalan.Base.$bang$bang$bang(Base.scala:35)
	at sigmastate.eval.Evaluation.$anonfun$compile$2(Evaluation.scala:655)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at scala.collection.AbstractMap.getOrElse(Map.scala:63)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:655)
	... 66 more
```

**Comment by jasondavies** [comment]
The above error can be reproduced using the `/script/executeWithContext` API.

**Comment by jasondavies** [comment]
Even more minimal:

```
{
  val t = {(b: Box) => true}

  true && OUTPUTS.exists(t)
}
```

**Comment by jasondavies** [comment]
> Strangely, changing the order of the last line makes the error go away.

I'm guessing this is due to a bug in lazy evaluation.

**Comment by aslesarenko** [comment]
This is a bug in costing, similar to what I found before. This has to do with bad interaction of lambda with lazy scope of right argument (thunk). Hopefully fixed in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/568, which means it requires HF.

**Comment by greenhat** [comment]
Ok, I’m closing it.

**Comment by aslesarenko** [comment]
Nope, it is not fixed in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/568, so this is something new. Anyway it will require HF.
