### ISSUE TITLE
Light node with pruning can't catch after long shutdown 

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1159]
After long enough shutdown a light node with pruning can't catch up, errors in the log are like:

18:51:28.121 WARN  [ctor.default-dispatcher-8] o.e.n.ErgoNodeViewSynchronizer - Modifier 7ca83513fcfb59599928e564d5a8bd2e4568271e0b1f3ec10024670b8ec17b09 is permanently invalid
scorex.core.validation.MalformedModifierError: Block section should correspond to a block header that is not pruned yet. header=92a2ce3734d63cbed461ec0a320d2956170f24e0117344bff901f0549d43c8ca, id=7ca83513fcfb59599928e564d5a8bd2e4568271e0b1f3ec10024670b8ec17b09
	at scorex.core.validation.ModifierValidator$.fatal(ModifierValidator.scala:44)
	at org.ergoplatform.settings.ValidationRules$.fatal(ValidationRules.scala:298)
	at org.ergoplatform.settings.ValidationRules$.$anonfun$rulesSpec$42(ValidationRules.scala:151)
	at org.ergoplatform.settings.ErgoValidationSettings.$anonfun$getError$1(ErgoValidationSettings.scala:33)
	at scala.Option.map(Option.scala:230)
	at org.ergoplatform.settings.ErgoValidationSettings.getError(ErgoValidationSettings.scala:33)
	at scorex.core.validation.ValidationState.$anonfun$validate$1(ModifierValidator.scala:93)
	at scorex.core.validation.ValidationState.pass(ModifierValidator.scala:72)
	at scorex.core.validation.ValidationState.validate(ModifierValidator.scala:93)
	at org.ergoplatform.nodeView.history.storage.modifierprocessors.FullBlockSectionProcessor$PayloadValidator.validate(FullBlockSectionProcessor.scala:101)
	at org.ergoplatform.nodeView.history.storage.modifierprocessors.FullBlockSectionProcessor.$anonfun$validate$1(FullBlockSectionProcessor.scala:47)
	at scala.Option.map(Option.scala:230)
	at org.ergoplatform.nodeView.history.storage.modifierprocessors.FullBlockSectionProcessor.validate(FullBlockSectionProcessor.scala:45)
	at org.ergoplatform.nodeView.history.storage.modifierprocessors.FullBlockSectionProcessor.validate$(FullBlockSectionProcessor.scala:44)
	at org.ergoplatform.nodeView.history.ErgoHistory$$anon$3.validate(ErgoHistory.scala:232)
	at org.ergoplatform.nodeView.history.ErgoHistoryReader.applicableTry(ErgoHistoryReader.scala:217)
	at org.ergoplatform.nodeView.history.ErgoHistoryReader.applicableTry$(ErgoHistoryReader.scala:212)
	at org.ergoplatform.nodeView.history.ErgoHistory$$anon$3.applicableTry(ErgoHistory.scala:232)
	at org.ergoplatform.nodeView.history.ErgoHistory$$anon$3.applicableTry(ErgoHistory.scala:232)
	at scorex.core.network.NodeViewSynchronizer.scorex$core$network$NodeViewSynchronizer$$validateAndSetStatus(NodeViewSynchronizer.scala:296)
	at scorex.core.network.NodeViewSynchronizer$$anonfun$modifiersFromRemote$1.$anonfun$applyOrElse$12(NodeViewSynchronizer.scala:281)
	at scorex.core.network.NodeViewSynchronizer$$anonfun$modifiersFromRemote$1.$anonfun$applyOrElse$12$adapted(NodeViewSynchronizer.scala:281)
	at scala.collection.TraversableLike.noneIn$1(TraversableLike.scala:271)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:337)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at scorex.core.network.NodeViewSynchronizer$$anonfun$modifiersFromRemote$1.applyOrElse(NodeViewSynchronizer.scala:281)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at scorex.core.network.NodeViewSynchronizer.aroundReceive(NodeViewSynchronizer.scala:43)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by dimension-drifter** [comment]
@kushti i have raised a PR for this issue. Please Review it
