### ISSUE TITLE
[BUG] - java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mark-stopka** [ergoplatform/ergo#1260]
Node crashes with `java.lang.OutOfMemoryError: Java heap space`, node version `ergo-3.3.7.jar` on Windows 10:
```
[ERROR] [SECURITY][01/03/2021 23:07:50.684] [ergoref-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(ergoref)] Uncaught error from thread [ergoref-akka.actor.default-dispatcher-5]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ergoref]
java.lang.OutOfMemoryError: Java heap space
        at akka.util.ByteIterator.getBytes(ByteIterator.scala:601)
        at scorex.core.network.message.MessageSerializer.$anonfun$deserialize$1(MessageSerializer.scala:63)
        at scorex.core.network.message.MessageSerializer$$Lambda$2243/20295274.apply(Unknown Source)
        at scala.util.Try$.apply(Try.scala:213)
        at scorex.core.network.message.MessageSerializer.deserialize(MessageSerializer.scala:38)
        at scorex.core.network.PeerConnectionHandler$$anonfun$remoteInterface$1.process$1(PeerConnectionHandler.scala:194)
        at scorex.core.network.PeerConnectionHandler$$anonfun$remoteInterface$1.applyOrElse(PeerConnectionHandler.scala:215)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at scorex.core.network.PeerConnectionHandler.aroundReceive(PeerConnectionHandler.scala:22)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by kushti** [comment]
@mark-stopka try to launch it with -Xmx3G flag, e.g. 
java -jar -Xmx3G -Dlogback.stdout.level=DEBUG ergo.jar  --mainnet -c mainnet.conf

**Comment by mark-stopka** [comment]
Thanks, I've got the following error:

```
Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
```

which led me to the fact that the issue may be related to 32-bit Java, so I installed `x86_64` version, let me see how that will go, I have also applied the parameters you have specified. Let's see if the issue is solved...

**Comment by kushti** [comment]
@mark-stopka thanks! Yes, I guess 64 bit Java is needed for 3GB. you can run light-fullnode on 32 bits and 512 MB limit even, but that's not suitable for mining
