### ISSUE TITLE
Synchronisation stops when no disk space left on device

### ISSUE THREAD

**Issue by jasondavies** [ergoplatform/ergo#1261]
```
11:22:00.892 ERROR [ctor.default-dispatcher-4] s.c.a.a.b.VersionedLDBAVLStorage - Failed to update tree
org.iq80.leveldb.DBException: IO error: /home/jason/ergo/.ergo/state/ldb_main/096669.log: No space left on device
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
        at scorex.db.StoreRegistry$RegisteredDB.write(LDBFactory.scala:42)
        at scorex.db.LDBVersionedStore.update(LDBVersionedStore.scala:219)
        at scorex.crypto.authds.avltree.batch.VersionedLDBAVLStorage.$anonfun$update$1(VersionedLDBAVLStorage.scala:60)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at scorex.crypto.authds.avltree.batch.VersionedLDBAVLStorage.update(VersionedLDBAVLStorage.scala:52)
        at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.generateProofAndUpdateStorage(PersistentBatchAVLProver.scala:25)
        at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$2(UtxoState.scala:113)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:110)
        at scala.util.Success.flatMap(Try.scala:251)
        at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:109)
        at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:34)
        at scorex.core.NodeViewHolder.$anonfun$applyState$1(NodeViewHolder.scala:249)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
        at scorex.core.NodeViewHolder.applyState(NodeViewHolder.scala:247)
        at scorex.core.NodeViewHolder.applyState$(N11:22:00.947 INFO  [tor.default-dispatcher-17] s.c.n.PeerConnectionHandler - Received message MessageSpec(55: Inv) from ConnectionId(remote=/X.X.X.X:YYYY, local=/X.X.X.X:YYYYY, direction=Outgoing)
```

Even after freeing disk space and restarting the node, it stops downloading new blocks.

**Comment by kushti** [comment]
@jasondavies the same message after freeing the space ?

**Comment by jasondavies** [comment]
@kushti No, after restarting the node, it simply fails to synchronise properly without any obvious errors. I see messages like:

```
11:22:58.740 DEBUG [ctor.default-dispatcher-8] o.e.n.ErgoNodeViewSynchronizer - Comparison with ConnectedPeer(ConnectionId(remote=/X.X.X.X:YYYY, local=/X.X.X.X/YYYY, direction=Outgoing)) having starting points [(101,67243fb7c4bc8066d07d1ea398b0965c2ab6f315e1bdd711d016cc93660f9844)..(101,bcad97803a2f32cc7ea6fff5524639c057a663411d85aecf88b2802086740db1)]. Comparison result is Older. Sending extension of length 400
```

It's stuck in some kind of invalid state where it fails to synchronise the chain - it's not obvious why.  I would suggest setting up a test node with data on a small disk partition, fully synchronising and then forcing it to run out of space by creating a large file.  Then shut down the node and use a snapshot of the data folder to test any fixes.

**Comment by Willburn** [comment]
Related to this issue of disk space running out - suggestion; Log file customization to set max file size. Miner should have this as well as how node has this in xml and preferably easy to just set in the config.json file. I suggest this is all done in the config.json if possible since this is where the user will customize the settings of the node most easily.
