### ISSUE TITLE
Installation from scratch doesn't work properly

### ISSUE THREAD

**Issue by alter** [ergoplatform/ergo#1350]
java -jar /opt/ergo/ergo.jar --mainnet  
```
14:48:44.734 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(None,Some(MainNet))
14:48:44.759 INFO  [main] o.e.settings.ErgoSettings$ - Running in mainnet network mode
14:48:44.760 WARN  [main] o.e.settings.ErgoSettings$ - NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS!
Exception in thread "main" com.typesafe.config.ConfigException$Missing: /tmp/mainnet.conf: 1: No configuration setting found for key 'ergo.directory'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at net.ceedubs.ficus.readers.StringReader$$anon$1.read(StringReader.scala:7)
	at net.ceedubs.ficus.readers.StringReader$$anon$1.read(StringReader.scala:6)
	at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
	at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
	at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:21)
	at org.ergoplatform.settings.ErgoSettings$.fromConfig(ErgoSettings.scala:57)
	at org.ergoplatform.settings.ErgoSettings$.read(ErgoSettings.scala:53)
	at org.ergoplatform.ErgoApp.<init>(ErgoApp.scala:36)
	at org.ergoplatform.ErgoApp$.main(ErgoApp.scala:203)
	at org.ergoplatform.ErgoApp.main(ErgoApp.scala)
```

**Comment by kushti** [comment]
Please run with a config: java -jar /opt/ergo/ergo.jar --mainnet mainnet.conf

Simplest config is :

ergo {
  networkType = "mainnet"
}

scorex {

 restApi {
   // API key == "hello" (without quotes)  
   apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"	
 }
}

**Comment by alter** [comment]
if launch it manually It works with config, but I've launched it with installation bash-script and there is no point to config

**Comment by amrbz** [comment]
This configuration worked for me:

## myergo.conf
```
ergo {
  node {
    mining = false
  }
  networkType="mainnet"
}

scorex {
  restApi {
    // API key == "hello" (without quotes)
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}
```

## docker-compose.yml

```
version: "2"

services:
  node:
    image: ergoplatform/ergo
    container_name: ergo-mainnet
    ports:
      - 9053:9053
      - 9030:9030
    environment:
      - MAX_HEAP=3G
    volumes:
      - ~/.data/ergo/mainnet:/home/ergo/.ergo
      - ./myergo.conf:/etc/myergo.conf
    restart: unless-stopped
    command: --mainnet -c /etc/myergo.conf
```

Run the node with
```
docker-compose up -d
```

Follow the logs with
```
docker logs -f ergo-mainnet -n 200
```
