### ISSUE TITLE
Having basic install issues

### ISSUE THREAD

**Issue by BountyHAHC** [ergoplatform/ergo#1370]
Downloaded current Java
Ergo Protocol Reference Client 4.0.11 - will not install and or open properly

C:\Users\Alexi H Cholakian\Downloads>java -jar ergo-4.0.11.jar
11:23:14.106 INFO  [main] org.ergoplatform.ErgoApp - Running with args: Args(None,None)
11:23:14.123 WARN  [main] o.e.settings.ErgoSettings$ - Running without network config
11:23:14.679 INFO  [main] org.ergoplatform.ErgoApp - Working directory: C:\Users\Alexi H Cholakian\Downloads/.ergo
11:23:14.679 INFO  [main] org.ergoplatform.ErgoApp - Secret directory: C:\Users\Alexi H Cholakian\Downloads/.ergo/wallet/keystore
11:23:14.887 INFO  [ctor.default-dispatcher-5] s.c.n.NetworkController - Declared address: None
11:23:14.901 INFO  [tor.default-dispatcher-11] s.c.n.NetworkController - Registering handlers for List((1,GetPeers message), (2,Peers message))
11:23:14.905 WARN  [ergoref-api-dispatcher-7] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
11:23:14.913 INFO  [ctor.default-dispatcher-5] s.c.n.NetworkController - Registering handlers for List((55,Inv), (22,RequestModifier), (33,Modifier), (65,Sync))
11:23:14.993 INFO  [tor.default-dispatcher-10] s.c.u.NetworkTimeProvider - New offset adjusted: -822
11:23:15.068 ERROR [tor.default-dispatcher-10] s.c.n.NetworkController - Network port 9020 already in use!
[ERROR] [05/27/2021 11:23:15.069] [ergoref-akka.actor.internal-dispatcher-4] [akka://ergoref/system/IO-TCP/selectors/$a/0] Bind failed for TCP channel on endpoint [/0.0.0.0:9020]
java.net.BindException: [/0.0.0.0:9020] Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:60)
        at akka.io.TcpListener.<init>(TcpListener.scala:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at akka.util.Reflect$.instantiate(Reflect.scala:73)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:226)
        at akka.actor.ActorCell.newActor(ActorCell.scala:613)
        at akka.actor.ActorCell.create(ActorCell.scala:640)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
        at akka.dispatch.Mailbox.run(Mailbox.scala:230)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by nevata** [comment]
port 9020 already in use

**Comment by BountyHAHC** [comment]
i just follow online instructions - the damn.jar file wouldn't even open on a brand new installed PC - i am just happy i got it to work - didnt get to a screen that i could input anything - i just sent this to get some help

**Comment by kushti** [comment]
Please check programs using ports as described in https://windowsloop.com/check-ports-in-use-windows-10/

And if you want to use mainnet please run as java -jar -Xmx3G  ergo-4.0.11.jar  --mainnet -c mainnet.conf , where mainnet.conf contains something like 


ergo {
  networkType = "mainnet"
}

scorex {

 restApi {	
    # Hex-encoded Blake2b256 hash of an API key. Should be 64-chars long Base16 string.
    # API KEY is "hello" (without quotes) with the hash value below
    apiKeyHash = "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
  }
}

**Comment by glasgowm148** [comment]
Please join the support channels or open a new issue if the problem persists
