### ISSUE TITLE
Advised / not advised to run node on MacOS?

### ISSUE THREAD

**Issue by mikew1** [ergoplatform/ergo#1381]
I've got the node running and synced on a Debian vm in VirtualBox - /panel at :9053 reports 'fully synced'.

Then I decided to try it directly on MacOS.  This isn't documented anywhere I could see, however I did see a screenshot of the panel running on localhost in safari somewhere in the wiki, so was curious.

Idea being I could potentially mine (that'd be stage 2) on a mac gpu, plus the benefit of avoiding the extra layer of a vm.  So I went ahead and tried it, installing the latest JDK, 16.

The node downloaded all the blocks and synced fine; panel showed node is synced. I then did Control-C, and shortly after tried running it again. This is where I hit a problem: out of memory error and was thrown back to the prompt. Reviewed the logs, then tried it again to see if got the same thing. Memory usage ~4G (didn't use any Xmx options). Then very high cpu usage with no further log output. So I eventually did Control-C on that. 

To cross check, I went back to the debian vm and ran the same (with same ergo.jar and conf) - that synced fine in a couple of minutes. java -version on the vm say Java11, not Java16 as I put on mac.

Questions:  Is ergo node ok to run directly on MacOS?  Is Java11 preferred over Java16?

Thanks a lot for any suggestions...

**Comment by mikew1** [comment]
I switched to java 11, and got this:

```
13:17:48.071 INFO  [tor.default-dispatcher-13] s.c.n.PeerConnectionHandler - Peer handler to ConnectionId(remote=/165.227.26.175:9030, local=/192.168.2.25:57352, direction=Outgoing) destroyed
[INFO] [akkaDeadLetter][06/04/2021 13:17:48.074] [ergoref-akka.actor.default-dispatcher-5] [akka://ergoref/user/networkController] Message [scorex.core.network.NetworkController$ReceivableMessages$ShutdownNetwork$] to Actor[akka://ergoref/user/networkController#923394997] was not delivered. [6] dead letters encountered. If this is not an expected behavior then Actor[akka://ergoref/user/networkController#923394997] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[WARN] [06/04/2021 13:17:48.108] [Thread-0] [CoordinatedShutdown(akka://ergoref)] Could not addJvmShutdownHook, due to: Shutdown in progress
13:17:48.122 INFO  [tor.default-dispatcher-10] o.e.local.MempoolAuditor - Mempool auditor stopped
[ERROR] [06/04/2021 13:17:48.344] [ergoref-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(ergoref)] Rendering of response failed because response entity stream materialization failed with 'cannot create children while terminating or terminated'. Sending out 500 response instead.
java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:291)
	at akka.actor.dungeon.Children.attachChild(Children.scala:52)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:51)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:410)
	at akka.stream.impl.ExtendedActorMaterializer.actorOf(ActorMaterializerImpl.scala:68)
	at akka.stream.impl.GraphStageIsland.onIslandReady(PhasedFusingActorMaterializer.scala:819)
	at akka.stream.impl.IslandTracking.allNestedIslandsReady(PhasedFusingActorMaterializer.scala:370)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:551)
	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:124)
	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:112)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:741)
	at akka.stream.scaladsl.Source.runWith(Source.scala:118)
	at akka.http.impl.engine.rendering.HttpResponseRendererFactory$HttpResponseRenderer$$anon$1.akka$http$impl$engine$rendering$HttpResponseRendererFactory$HttpResponseRenderer$$anon$$transfer(HttpResponseRendererFactory.scala:141)
	at akka.http.impl.engine.rendering.HttpResponseRendererFactory$HttpResponseRenderer$$anon$1$$anon$2.onPush(HttpResponseRendererFactory.scala:86)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[ERROR] [06/04/2021 13:17:53.364] [ergoref-akka.actor.default-dispatcher-12] [akka.dispatch.Dispatcher] Futures timed out after [5000 milliseconds]
java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3118)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:109)
	at scala.concurrent.Await$.result(package.scala:146)
	at akka.actor.LightArrayRevolverScheduler.close(LightArrayRevolverScheduler.scala:164)
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:1119)
	at akka.actor.ActorSystemImpl.$anonfun$_start$1(ActorSystem.scala:1024)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.actor.ActorSystemImpl$$anon$2.run(ActorSystem.scala:1046)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1278)
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$addRec$1$1.applyOrElse(ActorSystem.scala:1278)
	at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:536)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

13:17:53.366 INFO  [ctor.default-dispatcher-9] org.ergoplatform.ErgoApp - Exiting from the app...
13:17:53.366 WARN  [shutdownHook2] org.ergoplatform.ErgoApp$ - Application has been terminated.
m@mini-2 ergo % 
```

**Comment by mikew1** [comment]
Tried it with `-Xmx8G` and still got out of heap space.  Does it need more than 8G ram?

**Comment by mikew1** [comment]
On the main github page for ergo there's an image of the Node Interface [being accessed in Safari at 127.0.0.1](https://github.com/ergoplatform/ergo#ui).

That's maybe what set me down this path to believe the node could also run on MacOS. 
But is the screenshot there actually the node running on a virtual machine (or docker), with port forwarding?

Would just help to clear this up, thanks a lot.

**Comment by mikew1** [comment]
I think I'm grasping now that your favoured way to run Ergo on mac seems to be with docker, which likely explains the screenshot. (and that you likely won't have tried accessing mac gpu's - understandable).

My thinking on docker had been that it's about containerisation (in the sense of orchestration), but note now that in fact it's being used here just for scripting (related to containerisation). In this case, as an easy way to acquire a linux guest on a non-linux host. I was doing this manually with virtualbox, but can see docker works for this (accepting that use of docker has a different purpose this way than if it was used on linux host - here, it's just for scripting, we don't care about containerisation in the sense of orchestration here; original purpose of docker on linux).
