### ISSUE TITLE
Cannot setup a Node on mac os x

### ISSUE THREAD

**Issue by AlexPalaz** [ergoplatform/ergo#1432]
Hi, I'm trying to set up a full node on mac os x catalina. I followed all the instructions and the video tutorial, but when I run java command from terminal I continue to receive the following error:

`09:58:09.043 WARN  [main] o.e.settings.ErgoSettings$ - NO CONFIGURATION FILE WAS PROVIDED. STARTING WITH DEFAULT SETTINGS!
Exception in thread "main" com.typesafe.config.ConfigException$Missing: /var/folders/9w/rl9m064n7ljcwqrb2rg42qrh0000gn/T/mainnet.conf: 1: No configuration setting found for key 'ergo.directory'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at net.ceedubs.ficus.readers.StringReader$$anon$1.read(StringReader.scala:7)
	at net.ceedubs.ficus.readers.StringReader$$anon$1.read(StringReader.scala:6)
	at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
	at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
	at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:21)
	at org.ergoplatform.settings.ErgoSettings$.fromConfig(ErgoSettings.scala:57)
	at org.ergoplatform.settings.ErgoSettings$.read(ErgoSettings.scala:53)
	at org.ergoplatform.ErgoApp.<init>(ErgoApp.scala:36)
	at org.ergoplatform.ErgoApp$.main(ErgoApp.scala:219)
	at org.ergoplatform.ErgoApp.main(ErgoApp.scala)
`

My conf:

`ergo {
  node {
    mining = false
  }
}`

I'm running the terminal command from the ergo folder

**Comment by Ergonaumics** [comment]
I was unable to get it running in Catalina whatsoever, due to Catalinas lack of java support I believe.
