### ISSUE TITLE
Candidate is generated for 0 transactions

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo#1472]
When starting node with `mining = true` this happens very frequently : 
```
java.lang.IllegalArgumentException: Proofs for 0 txs cannot be generated : emissionTxs: 1, priorityTxs: 0, poolTxs: 0                                                                                              
        at org.ergoplatform.mining.CandidateGenerator$.$anonfun$createCandidate$1(CandidateGenerator.scala:501)                                                                                                            at scala.util.Try$.apply(Try.scala:213)                                                                                                                                                                    
        at org.ergoplatform.mining.CandidateGenerator$.createCandidate(CandidateGenerator.scala:411)                                                                                                               
        at org.ergoplatform.mining.CandidateGenerator$.generateCandidate(CandidateGenerator.scala:380)                                                                                                             
        at org.ergoplatform.mining.CandidateGenerator$$anonfun$org$ergoplatform$mining$CandidateGenerator$$initialized$1.applyOrElse(CandidateGenerator.scala:163)                                                 
        at akka.actor.Actor.aroundReceive(Actor.scala:537)                                                                                                                                                                 at akka.actor.Actor.aroundReceive$(Actor.scala:535)                                                                                                                                                        
        at org.ergoplatform.mining.CandidateGenerator.aroundReceive(CandidateGenerator.scala:49)                                                                                                                   
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)                                                                                                                                                
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)                                                                                                                                                        
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)                                                                                                                                                         at akka.dispatch.Mailbox.run(Mailbox.scala:231)                                                                                                                                                            
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)                                                                                                                                                                   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)                                                                                                                               
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)                                                                                                              
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)                                                                                                                                
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)                                                                                                                           
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)                                                                                                                  
```

Probably this is expected and we should not try to generate candidate in this case.

**Comment by pragmaxim** [comment]
@kushti I think I fixed this in https://github.com/ergoplatform/ergo/pull/1412 ... I noticed after I created this issue

**Comment by kushti** [comment]
I guess related to #1496
