### ISSUE TITLE
Investigate Double application of modifier error

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo#1531]
We try to store block modifier twice, most likely we receive a block modifier twice from remote peer. Modifier IDs are all different so it does not happen for a single one. See : 
```
org.ergoplatform.nodeView.ErgoNodeViewHolder#processRemoteModifiers
org.ergoplatform.nodeView.ErgoModifiersCache#findCandidateKey
```

```
11:57:50.804 WARN  [ctor.default-dispatcher-5] o.e.n.ErgoModifiersCache - Modifier 9abba2f298f4278a748db2be081bee15816653ea3fd870eecc21f6eace0f24ed is permanently invalid and will be removed from cache
```
and double application error : 
```
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 465b69b4431892142e5bd8c232c41bf4a0787499e9488253712fa869970a6d4d                                            
        at scorex.core.validation.ModifierValidator$.fatal(ModifierValidator.scala:44)                                                                                                                     
        at org.ergoplatform.settings.ValidationRules$.fatal(ValidationRules.scala:310)                                                                                                                     
        at org.ergoplatform.settings.ValidationRules$.$anonfun$rulesSpec$1(ValidationRules.scala:22)                                                                                                       
        at org.ergoplatform.settings.ErgoValidationSettings.$anonfun$getError$1(ErgoValidationSettings.scala:33)                                                                                           
        at org.ergoplatform.nodeView.history.storage.modifierprocessors.FullBlockSectionProcessor$PayloadValidator.validate(FullBlockSectionProcessor.scala:97)
```
see : 
```
[15:09:43.306] $ cat  nohup.out | grep -I "permanently invalid"  | wc -l
63326
[15:09:47.169] $ cat  nohup.out | grep "Double application" | wc -l
63326
```

**Comment by pragmaxim** [comment]
My bad, sorry... It is not supposed to be created

**Comment by pragmaxim** [comment]
@kushti I might find the reason, we are frequently pulling for next blocks to download but WHAT to pull is actually determined by this strange `lastBlockHeight - 100` rule which I do not understand : 

https://github.com/ergoplatform/ergo/blob/246ac2918028462a07dff19ea1ca35e4e15bb5e0/src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/ToDownloadProcessor.scala#L73

**Comment by kushti** [comment]
@pragmaxim this rule is about downloading block sections corresponding to children of last 100 best headers (so forks started from 100 blocks ago or later). 

Filtering is done via *condition: ModifierId => Boolean* argument, which is instantiated with 

```
private def downloadRequired(historyReader: ErgoHistory)(id: ModifierId): Boolean = {
    deliveryTracker.status(id, Array(historyReader)) == ModifiersStatus.Unknown
}
```
