### ISSUE TITLE
Logging Levels Features

### ISSUE THREAD

**Issue by solopool** [ergoplatform/ergo#1546]
Hello!

In the process of working in the logs, we have a lot of information. It would be great to give the config it is possible to set the logging level.

Example: **OFF, FATAL, ERROR, WARN, INFO, DEBUG** or something similar.

Now it is not even possible to set the path with the main log file.

**Comment by kushti** [comment]
Run as e.g. 

```java -jar -Xmx3G -Dlogback.stdout.level=WARN -Dlogback.file.level=WARN ergo-4.0.17.jar  --mainnet -c mainnet.conf```

```-Dlogback.stdout.level=WARN```  to reduce console output to WARN and ERR messages only

```-Dlogback.file.level=WARN``` - to reduce ergo.log

possible levels are TRACE , DEBUG, INFO, WARN, ERROR (INFO is default)

**Comment by kushti** [comment]
Please lmk if you need for a path setting also

otherwise, please close the issue

**Comment by kushti** [comment]
or, better, reopen it if there are any questions left.

**Comment by solopool** [comment]
Hello!

> java -jar -Xmx3G -Dlogback.stdout.level=WARN -Dlogback.file.level=WARN ergo-4.0.17.jar --mainnet -c mainnet.conf

```
14:36:11.099 WARN  [ergoref-api-dispatcher-9] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
14:36:11.177 WARN  [ctor.default-dispatcher-4] o.e.settings.ErgoSettings$ - Running without network config
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:74)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.TraversableOnce.addString(TraversableOnce.scala:362)
        at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:358)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1429)
        at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
        at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:327)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
        at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:330)
        at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:330)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
        at org.ergoplatform.ErgoApp.swaggerConfig(ErgoApp.scala:164)
        at org.ergoplatform.ErgoApp.<init>(ErgoApp.scala:135)
        at org.ergoplatform.ErgoApp$.$anonfun$main$1(ErgoApp.scala:221)
        at scala.Option.foreach(Option.scala:407)
        at org.ergoplatform.ErgoApp$.main(ErgoApp.scala:220)
        at org.ergoplatform.ErgoApp.main(ErgoApp.scala)
14:36:13.113 WARN  [ergoref-api-dispatcher-9] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
14:36:15.133 WARN  [ergoref-api-dispatcher-9] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
14:36:17.152 WARN  [ergoref-api-dispatcher-9] o.e.n.ErgoReadersHolder - Got GetReaders request in state (None,None,None,None)
```


Config doesn't read with these options.
