### ISSUE TITLE
non-deterministic test failures due to `Random` in generators

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo#1558]
There are a few tests failing once in a while, like : 
```
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: Invalidated(scorex.core.validation.MalformedModifierError: Scripts of all transaction inputs should pass verification. c47d06c4e3fa9679aa3389d34807c90e5740dce7269eedc78d5bfaae579822ea: #0 => Success((false,37641))) was not equal to Accepted
[info]     Location: (ErgoMemPoolSpec.scala:88)
```
OR 
```
[pool-1-thread-1-ScalaTest-running-CandidateGeneratorPropSpec] >> [WARN ] o.e.nodeView.state.UtxoState >> 12:43:19.673 Error while applying full block with header 2fd5f9392a4822421b06f53b85ea3204e81464a6b6d6cc4f5bf69b12b527aaf6 to UTXOState with root 93914ecff82cea3b53b32d0f0527069f7361ef3b426271235eb6f4d76337900202, reason: scorex.core.validation.MalformedModifierError: Scripts of all transaction inputs should pass verification. 42f9b2a64fc98798e43cade15fa759f9ae0cc3956bd4b6e6d3cc93b571e873c3: #0 => Success((false,23533)) 
[info] - collect reward from emission box only
[pool-1-thread-1-ScalaTest-running-CandidateGeneratorPropSpec] >> [WARN ] o.e.nodeView.state.UtxoState >> 12:43:19.869 Error while applying full block with header 3cec9e334280df892dbb245245174f09748a7929647d34ffee05012930f75901 to UTXOState with root a0eb6c802f971d97163ba551fe7e98d4914aaa48d71344dfa7bc351d4bcb9d7b0d, reason: scorex.core.validation.MalformedModifierError: Scripts of all transaction inputs should pass verification. e1d4e5991b2374fbe76eb4b5338c87896176dec0a1100823277d09e0a8fdf594: #0 => Success((false,15188)) 
[pool-1-thread-1-ScalaTest-running-CandidateGeneratorPropSpec] >> [WARN ] o.e.nodeView.state.UtxoState >> 12:43:19.879 Emission box not found in block fe4cfc9d85c5f06200e011608a83bda20fc46bac040da660cba669642b26d096
[info] - collect reward from transaction fees only
[info] - filter out double spend txs
[info] - should only collect valid transactions *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed
[info]   at scala.Predef$.require(Predef.scala:268)
[info]   at org.ergoplatform.utils.generators.ErgoTransactionGenerators.validUnsignedTransactionFromBoxes(ErgoTransactionGenerators.scala:133)
[info]   at org.ergoplatform.utils.generators.ErgoTransactionGenerators.validUnsignedTransactionFromBoxes$(ErgoTransactionGenerators.scala:113)
[info]   at org.ergoplatform.mining.CandidateGeneratorPropSpec.validUnsignedTransactionFromBoxes(CandidateGeneratorPropSpec.scala:17)
[info]   at org.ergoplatform.utils.generators.ErgoTransactionGenerators.validTransactionFromBoxes(ErgoTransactionGenerators.scala:205)
[info]   at org.ergoplatform.utils.generators.ErgoTransactionGenerators.validTransactionFromBoxes$(ErgoTransactionGenerators.scala:199)
[info]   at org.ergoplatform.mining.CandidateGeneratorPropSpec.validTransactionFromBoxes(CandidateGeneratorPropSpec.scala:17)

```
because the block components are generated using Random numbers and sometimes it overflows the max block cost ... we need to either increase max block cost for the tests or improve the randomization .

**Comment by pragmaxim** [comment]
Fixed https://github.com/ergoplatform/ergo/pull/1563

**Comment by pragmaxim** [comment]
`MempoolAuditorSpec` is left to fix, it is related to due to https://github.com/ergoplatform/ergo/issues/1608 : 

https://github.com/ergoplatform/ergo/blob/6a96896b3733882bac7784ab673a90ebe5fca29f/src/test/scala/org/ergoplatform/local/MempoolAuditorSpec.scala#L83
