### ISSUE TITLE
Tree root should be real but was UnprovenSchnorr

### ISSUE THREAD

**Issue by butterfly-sn** [ergoplatform/ergo#1710]
[2022-05-17 09:00:17.796]-[scheduled-task-pool-4 o.s.s.s.TaskUtils$LoggingErrorHandler]-[Unexpected error occurred in scheduled task]
java.lang.AssertionError: assertion failed: Tree root should be real but was UnprovenSchnorr(ProveDlog((a3c1a72753dd7d5530b9524090d9227734d43f2a737a9b2a6cb927bc39323dc3,22076816cc53b82efc86a3a386d34d142488c72c3d4f1a74c82cf09dbfd48c90,1)),None,None,None,true,0)
	at scala.Predef$.assert(Predef.scala:223)
	at sigmastate.interpreter.ProverInterpreter.prove(ProverInterpreter.scala:74)
	at sigmastate.interpreter.ProverInterpreter.prove$(ProverInterpreter.scala:67)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.prove(AppkitProvingInterpreter.scala:35)
	at sigmastate.interpreter.ProverInterpreter.$anonfun$prove$2(ProverInterpreter.scala:136)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.interpreter.ProverInterpreter.prove(ProverInterpreter.scala:118)
	at sigmastate.interpreter.ProverInterpreter.prove$(ProverInterpreter.scala:114)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.prove(AppkitProvingInterpreter.scala:35)
	at sigmastate.interpreter.ProverInterpreter.prove(ProverInterpreter.scala:112)
	at sigmastate.interpreter.ProverInterpreter.prove$(ProverInterpreter.scala:109)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.prove(AppkitProvingInterpreter.scala:35)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.$anonfun$sign$7(AppkitProvingInterpreter.scala:126)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.$anonfun$sign$1(AppkitProvingInterpreter.scala:107)
	at scala.util.Try$.apply(Try.scala:213)
	at org.ergoplatform.appkit.AppkitProvingInterpreter.sign(AppkitProvingInterpreter.scala:74)
	at org.ergoplatform.appkit.impl.ErgoProverImpl.sign(ErgoProverImpl.scala:28)
	at org.ergoplatform.appkit.impl.ErgoProverImpl.sign(ErgoProverImpl.scala:22)
	at com.bitmart.chain.service.tx.DefaultTransactionBuilder.build(DefaultTransactionBuilder.java:164)
	at com.bitmart.chain.service.tx.RawTransactionService.assemble(RawTransactionService.java:107)
	at com.bitmart.chain.service.withdraw.DefaultWithdrawService.generateTransaction(DefaultWithdrawService.java:95)
	at com.bitmart.chain.service.withdraw.DefaultWithdrawService.handleTodoRequests(DefaultWithdrawService.java:402)
	at com.bitmart.chain.service.withdraw.DefaultWithdrawService.lambda$null$7(DefaultWithdrawService.java:364)
	at java.util.ArrayList.forEach(ArrayList.java:1257)

**Comment by butterfly-sn** [comment]
When I built the transaction, he had such an error. I don't know what caused this. I used the node I built myself, and the synchronization was no problem.

**Comment by kushti** [comment]
This error indicates that the prover does not have a secret to prove (to sign). Please provide details on transaction you want to sign and signing context

**Comment by butterfly-sn** [comment]
BlockchainContext blockchainContext = new BlockchainContextBuilderImpl(new ApiClient(nodeUrl, "ApiKeyAuth", apiKey),
                new ExplorerApiClient(Utils.EXPLORE_API),
                NetworkType.MAINNET)
                .build();

        //iutput
        List<InputBox> inputBoxes = new ArrayList<>();
        //pk
        HashSet<BigInteger> pks = new HashSet<>();
        for (SenderDTO senderDTO : senders) {
            String box = senderDTO.getTxid();
            ErgoTransactionOutput ergoTransactionOutput = gson.fromJson(box, ErgoTransactionOutput.class);
            InputBox inputBox = new InputBoxImpl((BlockchainContextImpl) blockchainContext, ergoTransactionOutput);
            inputBoxes.add(inputBox);


            String address = senderDTO.getAddress();
            pks.add(generpk(address));
        }


        //output
        Address address = Address.create(withdrawRequestDTO.getToAddress());
        DLogProtocol.ProveDlog publicKey = address.getPublicKey();
        UnsignedTransactionBuilder txB = blockchainContext.newTxBuilder();
        OutBox outBox = txB.outBoxBuilder()
                .value(Utils.calChainAmount(withdrawRequestDTO.getAmount()))
                .contract(blockchainContext.compileContract(ConstantsBuilder.create()
                        .item("recipientPk", publicKey)
                        .build(), "{ recipientPk }"))
                .build();



        //charge address
        ErgoAddress chargeAddr = Address.create(chargeAddress).getErgoAddress();

        //unsign
        UnsignedTransaction unsignedTransaction = txB.boxesToSpend(inputBoxes).outputs(outBox).fee(Utils.MIN_FEE).sendChangeTo(chargeAddr).build();
        //sign

        ErgoProverBuilder ergoProverBuilder = blockchainContext.newProverBuilder();
        pks.forEach(ergoProverBuilder::withDLogSecret);

        SignedTransaction signedTransaction = ergoProverBuilder.build().sign(unsignedTransaction);
        String txid = signedTransaction.getId();
        log.info("txid : " + txid);
