### ISSUE TITLE
Double application error in light node logs

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1782]
`cat ergo-2022-07-26.0.log | grep 99780d79564ff8bbc630ca513868b2f1d10f7dd87d9bedf5b55a104973154bff`

```
14:51:33.436 INFO  [ctor.default-dispatcher-5] o.e.n.DigestNodeViewHolder - Apply modifier 99780d79564ff8bbc630ca513868b2f1d10f7dd87d9bedf5b55a104973154bff of type 101 to nodeViewHolder
14:51:33.451 INFO  [ctor.default-dispatcher-5] o.e.n.h.ErgoHistory$$anon$3 - New best header 99780d79564ff8bbc630ca513868b2f1d10f7dd87d9bedf5b55a104973154bff with score 972595672159361171456. New height 792402, old height 792401
14:51:39.673 WARN  [ctor.default-dispatcher-5] o.e.n.ErgoModifiersCache - Modifier 99780d79564ff8bbc630ca513868b2f1d10f7dd87d9bedf5b55a104973154bff is permanently invalid and will be removed from cache
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 99780d79564ff8bbc630ca513868b2f1d10f7dd87d9bedf5b55a104973154bff
```

**Comment by kushti** [comment]
happens in other modes as well:

```
07:37:59.386 INFO  [tor.default-dispatcher-13] o.e.n.ErgoNodeViewSynchronizer - Applying valid syncInfoV2 header 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
07:38:02.589 INFO  [tor.default-dispatcher-11] o.e.n.ErgoNodeViewSynchronizer - Applying valid syncInfoV2 header 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
07:38:03.293 INFO  [tor.default-dispatcher-14] o.e.n.ErgoNodeViewSynchronizer - Applying valid syncInfoV2 header 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
07:38:03.816 INFO  [ctor.default-dispatcher-8] o.e.n.ErgoNodeViewSynchronizer - Applying valid syncInfoV2 header 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151

07:43:12.141 WARN  [ctor.default-dispatcher-5] o.e.n.ErgoModifiersCache - Modifier 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151 is permanently invalid and will be removed from cache
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
07:43:12.144 WARN  [ctor.default-dispatcher-5] o.e.n.ErgoModifiersCache - Modifier 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151 is permanently invalid and will be removed from cache
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
07:43:12.146 WARN  [ctor.default-dispatcher-5] o.e.n.ErgoModifiersCache - Modifier 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151 is permanently invalid and will be removed from cache
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 0f16266aa385a139dd96881001374d868fe1559c083bae5644055bb44b385151
```

**Comment by pragmaxim** [comment]
This happens to me in default mode with latest release, after which the node got stuck : 
```
19:31:25.041 INFO  [tor.default-dispatcher-13] o.e.n.h.ErgoHistory$$anon$3 - New best header 61691e20d48d8650c22238f0bca1f43644fff35529d6dc61b8e3e70e3e635843 with score 1024623372873054027776. New height 830393, old height 830392
19:31:25.041 INFO  [tor.default-dispatcher-35] o.e.local.MempoolAuditor - Initiating cleanup. Switching to working mode
19:31:25.041 INFO  [tor.default-dispatcher-36] o.e.local.MempoolAuditor - Cleanup done. Switching to awaiting mode
19:31:25.042 WARN  [tor.default-dispatcher-11] o.e.n.ErgoModifiersCache - Modifier 61691e20d48d8650c22238f0bca1f43644fff35529d6dc61b8e3e70e3e635843 is permanently invalid and will be removed from cache
scorex.core.validation.MalformedModifierError: Double application of a modifier is prohibited. 61691e20d48d8650c22238f0bca1f43644fff35529d6dc61b8e3e70e3e635843 already applied
        at scorex.core.validation.ModifierValidator$.fatal(ModifierValidator.scala:45)
        at org.ergoplatform.settings.ValidationRules$.fatal(ValidationRules.scala:317)
        at org.ergoplatform.settings.ValidationRules$.$anonfun$rulesSpec$1(ValidationRules.scala:24)
        at org.ergoplatform.settings.ErgoValidationSettings.$anonfun$getError$1(ErgoValidationSettings.scala:33)
        at scala.Option.map(Option.scala:230)
```
