### ISSUE TITLE
Candidate generation failed:

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1804]
From one log :+1: 
```
ergo-node-mainnet_1  | 19:43:47.852 ERROR [tor.default-dispatcher-10] o.e.m.CandidateGenerator - Candidate generation failed
ergo-node-mainnet_1  | java.lang.Exception: Key 036efb6300eb404ce99a8c930173769071ed1118c288407b01823b3561f9ab00 does not exist
ergo-node-mainnet_1  | 	at scorex.crypto.authds.avltree.batch.Remove.$anonfun$updateFn$5(Operation.scala:68)
ergo-node-mainnet_1  | 	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:190)
ergo-node-mainnet_1  | 	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:239)
ergo-node-mainnet_1  | 	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:239)
ergo-node-mainnet_1  | 	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:211)
```

and then 

```
ergo-node-mainnet_1  | 19:43:53.916 ERROR [tor.default-dispatcher-10] o.e.m.CandidateGenerator - Candidate generation failed
ergo-node-mainnet_1  | java.lang.IllegalArgumentException: Proofs for 0 txs cannot be generated : emissionTxs: 1, priorityTxs: 0, poolTxs: 0
ergo-node-mainnet_1  | 	at org.ergoplatform.mining.CandidateGenerator$.$anonfun$createCandidate$1(CandidateGenerator.scala:537)
ergo-node-mainnet_1  | 	at scala.util.Try$.apply(Try.scala:213)
ergo-node-mainnet_1  | 	at org.ergoplatform.mining.CandidateGenerator$.createCandidate(CandidateGenerator.scala:442)
ergo-node-mainnet_1  | 	at org.ergoplatform.mining.CandidateGenerator$.generateCandidate(CandidateGenerator.scala:375)
ergo-node-mainnet_1  | 	at org.ergoplatform.mining.CandidateGenerator$$anonfun$org$ergoplatform$mining$CandidateGenerator$$initialized$1.applyOrElse(CandidateGenerator.scala:156)
```

**Comment by qu0b** [comment]
Candidate Generation should not stop if a transaction cannot be included but instead should continue without the transaction
