### ISSUE TITLE
Mining candidate block update

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#183]
Sometimes miner is failed to update candidate block, full height is 27042, last candidate is at  height 27041

**Comment by catena2w** [comment]
Looks like problem is in proving transactions:
```
[ergoref-akka.actor.default-dispatcher-17] >> [WARN ] org.ergoplatform.local.ErgoMiner >> 16:34:16.035 Error when trying to generate a block: 
java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method)
        at org.bouncycastle.crypto.digests.Blake2bDigest.update(Unknown Source)
        at scorex.crypto.hash.Blake2b256Unsafe.$anonfun$hash$1(Blake2b256Unsafe.scala:24)
        at scorex.crypto.hash.Blake2b256Unsafe.$anonfun$hash$1$adapted(Blake2b256Unsafe.scala:24)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
        at scorex.crypto.hash.Blake2b256Unsafe.hash(Blake2b256Unsafe.scala:24)
        at scorex.crypto.hash.Blake2b256Unsafe.prefixedHash(Blake2b256Unsafe.scala:20)
        at scorex.crypto.authds.avltree.batch.Leaf.computeLabel(BatchNode.scala:133)
        at scorex.crypto.authds.avltree.batch.Leaf.computeLabel$(BatchNode.scala:133)
        at scorex.crypto.authds.avltree.batch.ProverLeaf.computeLabel(BatchNode.scala:155)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.ProverLeaf.label(BatchNode.scala:155)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
        at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
        at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
        at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.digest(AuthenticatedTreeOps.scala:40)
        at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.digest$(AuthenticatedTreeOps.scala:33)
        at scorex.crypto.authds.avltree.batch.BatchAVLProver.digest(BatchAVLProver.scala:21)
        at scorex.crypto.authds.avltree.batch.BatchAVLProver.digest(BatchAVLProver.scala:148)
        at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.digest(PersistentBatchAVLProver.scala:13)
        at org.ergoplatform.nodeView.state.UtxoState.rollback$1(UtxoState.scala:131)
        at org.ergoplatform.nodeView.state.UtxoState.proofsForTransactions(UtxoState.scala:160)
        at org.ergoplatform.local.ErgoMiner.$anonfun$produceCandidate$3(ErgoMiner.scala:129)
        at scala.util.Try$.apply(Try.scala:209)
        at org.ergoplatform.local.ErgoMiner.$anonfun$produceCandidate$1(ErgoMiner.scala:106)
        at scorex.core.NodeViewHolder$$anonfun$getCurrentInfo$1.applyOrElse(NodeViewHolder.scala:378)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:23)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```
