### ISSUE TITLE
Ergo node can't sync over certain amount of blocks

### ISSUE THREAD

**Issue by HidenInTheDark** [ergoplatform/ergo#1974]
Version: 5.0.8
Command: java -jar -Xmx10G -Dlogback.stdout.level=WARN -Dlogback.file.level=ERR ergo.jar --mainnet -c ergo.conf
32GB DDR4/ Ryzen 7 3700x
Windows 11 Home
JDK 20
SSD NVMe (ergo wallet) HDD - blockchain
11:21:57.781 WARN  [ergoref-api-dispatcher-13] o.e.n.wallet.WalletVars - Trying to update prover's parameters, but prover is not initialized
11:25:15.448 WARN  [ef-critical-dispatcher-39] o.e.n.state.UtxoState - Error while applying full block with header bfe6c9298b491df49dc8ffa8b0f0400610a322287bdcca903ff7a0c2b40fd91e to UTXOState with root 5a505645c0a5ac2fac81f60c68bb9f5c31e0ad1f32a7f61c99e1eb9ba5e5126e13, reason: org.iq80.leveldb.DBException: Corruption: block checksum mismatch 
org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
	at scorex.db.StoreRegistry$RegisteredDB.write(LDBFactory.scala:42)
	at scorex.db.LDBVersionedStore.$anonfun$update$1(LDBVersionedStore.scala:282)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scorex.db.LDBVersionedStore.update(LDBVersionedStore.scala:236)
	at scorex.crypto.authds.avltree.batch.VersionedLDBAVLStorage.update(VersionedLDBAVLStorage.scala:64)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.generateProofAndUpdateStorage(PersistentBatchAVLProver.scala:25)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$3(UtxoState.scala:144)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$2(UtxoState.scala:140)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:137)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.$anonfun$applyState$1(ErgoNodeViewHolder.scala:235)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.applyState(ErgoNodeViewHolder.scala:228)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.updateState(ErgoNodeViewHolder.scala:202)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:454)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder$$anonfun$processRemoteModifiers$1.applyFromCacheLoop$1(ErgoNodeViewHolder.scala:293)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder$$anonfun$processRemoteModifiers$1.applyOrElse(ErgoNodeViewHolder.scala:343)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285)
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150)
	... 41 common frames omitted
11:25:15.454 WARN  [ef-critical-dispatcher-39] o.e.n.UtxoNodeViewHolder - Invalid modifier! Typeid: -127 id: bfe6c9298b491df49dc8ffa8b0f0400610a322287bdcca903ff7a0c2b40fd91e 
org.iq80.leveldb.DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
	at scorex.db.StoreRegistry$RegisteredDB.write(LDBFactory.scala:42)
	at scorex.db.LDBVersionedStore.$anonfun$update$1(LDBVersionedStore.scala:282)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scorex.db.LDBVersionedStore.update(LDBVersionedStore.scala:236)
	at scorex.crypto.authds.avltree.batch.VersionedLDBAVLStorage.update(VersionedLDBAVLStorage.scala:64)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.generateProofAndUpdateStorage(PersistentBatchAVLProver.scala:25)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$3(UtxoState.scala:144)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$2(UtxoState.scala:140)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:137)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.$anonfun$applyState$1(ErgoNodeViewHolder.scala:235)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.applyState(ErgoNodeViewHolder.scala:228)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.updateState(ErgoNodeViewHolder.scala:202)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:454)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder$$anonfun$processRemoteModifiers$1.applyFromCacheLoop$1(ErgoNodeViewHolder.scala:293)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder$$anonfun$processRemoteModifiers$1.applyOrElse(ErgoNodeViewHolder.scala:343)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: block checksum mismatch
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285)
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150)
	... 41 common frames omitted
I've deleated and reinstalled ergo.jar, reinstalled java, resynced node 10 times, nothing seems to help.
Please help ;-;

**Comment by kushti** [comment]
Looks like possible hardware or OS issues.

Some troubleshooting advices can be found https://github.com/bitcoin/bitcoin/issues/21724 (bitcoind is also using LevelDB)

**Comment by HidenInTheDark** [comment]
Nah, it finnaly fixed itself.
Had to reinstall java, change the launch script and select the NVME only.
