### ISSUE TITLE
Fix duplicate key in LSMStore `toUpdate` while applying full block to UtxoState

### ISSUE THREAD

**Issue by mike-aksarin** [ergoplatform/ergo#262]
Could be reproduced with `sbt test` command in `i191` branch of Ergo project.

```
[default-akka.actor.default-dispatcher-2] >> [INFO ] org.ergoplatform.local.ErgoMiner >> 19:38:58.078 Start candidate creation
[default-akka.actor.default-dispatcher-9] >> [INFO ] o.e.local.ErgoMiningThread >> 19:38:59.051 Trying to prove block with parent Some(CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU) and nonce 9216033560765603541
[default-akka.actor.default-dispatcher-9] >> [INFO ] o.e.local.ErgoMiningThread >> 19:38:59.062 New block found: ErgoFullBlock(Header({"difficulty":"1","votes":"UAj1rAf","timestamp":1524587938105,"nonce":0,"stateRoot":"4JXSUX6JqwEkCgKiWT1xd8RsfZgZkzwCDrEZeWcfXG9Mq","height":14,"nBits":16842752,"id":"51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3","interlinks":["6XBVm6WgfkJWMygupDrG4Ap1tWfsokZYdeLD2XJLKPKP","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU","CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU"],"adProofsRoot":"9wY3xaX5JJkzNMmrse6B7rtZggxE4gNZG2vvkJNgsub1","transactionsRoot":"Ab488usLgTMBHPMW2DYxNi42iWZrch78kKjN37NKTtQf","equihashSolutions":[899,428067329,1008735228,-1057363279,-663762405,-844381171,-869008167,-2055113492,1406932980,-502077935,-1628639353,-1234785935,941245627,2081430621,64560558,1784485178,648073236,-742950467,-1347502752,-1765414729,238293115,-1341146371,1760403529,977670385,-1936375912,2032008879,-1633252827,-230539535,-1960478761,1972286763,750582385,-1341554334],"parentId":"CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU"}),BlockTransactions(Id:D3BYG3wCJKY2mPUwP3tm5JvPq8dmZjoJHaDLhw7EGKPF,HeaderId:51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3,Txs:AnyoneCanSpendTransaction({"id":"B7ghP9jU9cDahXdYzSiD8hChtu1WxNR9vjYeYKLVWWBj","inputs":[{"id":"6aFqNhX3BAwX6RtixWwkQ6uU7NYzw8ubgCX1Cfy1yzRg","nonce":-4781070833158328187,"signature":""}],"outputs":[{"id":"HkfBtpQtm5eVyjjhY5v5az34gEQVtzdtYA6r1FaPZGVF","script":"","value":10000}]}),AnyoneCanSpendTransaction({"id":"GK3QeeQiVsdw8XjwnQVmGKajYDTNp7Zfc2tQ42eG9CCT","inputs":[{"id":"AUkreTK4tr9rpu7mXF1UPbVKsNSWuScZAP15ENjkickX","nonce":-6605660288395451698,"signature":""},{"id":"5zo2VNk72vtCaeUqhwUjtpLyLeyEuHWrVWg9FS25dobD","nonce":3353322156137068961,"signature":""},{"id":"CX4Dj6Kf63yob8ZfmCSMyqXe19vAW3MTZktp9XDy41qV","nonce":-7893995824752079753,"signature":""},{"id":"BLyrD4c5zzsDWic7g1oJ6d1d4U3BQKShPFnVcy5YeTUh","nonce":4765892643108154920,"signature":""},{"id":"EHyENjt7wZ1zS3cotNAM29YJLMZDbHNvbA34EawxHDhk","nonce":-4011041681507527315,"signature":""},{"id":"71G3XgG8ArQkYdoxNB1yTdW9PWmsiCAUThV9KVCRSB2c","nonce":-588138882381443708,"signature":""}],"outputs":[{"id":"Cp45MU5mzKL6qZnHcDprHQwWW2Ee4uJ5q8P52Z6rXm6s","script":"","value":5000},{"id":"HvXvQSCSfDq4maFSTQ2J4AhKPNjHTGtZoovUMzkSqNPK","script":"","value":5000},{"id":"68ZhisReBynuVBwqTQ6iTQLTibjeJJipEzr9E2q6xStv","script":"","value":10000},{"id":"BNazmK4br9Hv5ai2JF7pUZfS1H8eWsV5XjkzKVREVDQg","script":"","value":10000},{"id":"4WQSXxreLa81uJ6Hi5LBhkwmWPiFrMfLytAdof4DWktv","script":"","value":2500},{"id":"AttVuxDEFReYQcctCpcHFdGr9B35kBTQdZ1R1UZg4e6w","script":"","value":10000},{"id":"F1itqFZP7q6CHo9mYBbpFRvaRXr2JW3eqA9vrBtZC76h","script":"","value":5000}]}),AnyoneCanSpendTransaction({"id":"jAW8wKKvyw7eKRYonadWiGqS7nNDGWZWbMBw5GwcCNe","inputs":[{"id":"9FUadqRKCyVrCB3Mdwt5nPYq1BmdmPZH1LKZ1PU1Hgaf","nonce":-1002168347593793661,"signature":""},{"id":"5G3JVquVRMXGYBq9FQZTffYT7iWLffwkBx52TJTS5YXV","nonce":-95360794942129091,"signature":""},{"id":"51M9DLQLiiKDvbu2CXiqtkWK7Rmm2qQUTUjU2eVs5cdc","nonce":2978957001868682697,"signature":""},{"id":"FjUqDgVzqW7o3DHWGVW7DXmGJSQwu69uAoDEmrXuTTzz","nonce":8601982880744846945,"signature":""}],"outputs":[{"id":"9fHaZWc2DE2aVYLpqunKA6NaqsT5EHEG7fT4ZmsNqPNB","script":"","value":5000},{"id":"v9K2FggWPw517SkezrvybbcSArFZYmbMasMUwSNUPte","script":"","value":5000},{"id":"DFybW9gDzcridoDu6ntoU83UccWR4MfEp9oev7zb3Jqs","script":"","value":5000},{"id":"8XVnosCDSvnG6mK5HRXS12BXjp3Fvm8Cs21gtiaH6ra8","script":"","value":10000},{"id":"4Q5XvUU67oeFnmFsCBdki9iUtGbYiVUNud722FYtuuvx","script":"","value":10000}]}),AnyoneCanSpendTransaction({"id":"6hE3vmnykZ78ALKBpS4dyMMmJEb5txuzuKhTQouFMFNE","inputs":[{"id":"AZgq87H5W76qoDNbwfmjMQ2PgFYquZ25dLCZkjXxipCj","nonce":-5122930169561696428,"signature":""},{"id":"HMNMdkHxt7MVDdZH8b7KdUN6bio9hAFDqCbscrtVzwAv","nonce":-58056564152011059,"signature":""},{"id":"53DHYKv1PjfsV8Ep2Dno9xMU8E9wbVCp1AkNbQ3RU2th","nonce":-7754015857467888374,"signature":""}],"outputs":[{"id":"6o52cxgV27QyZTq3fZy8mg8wS723Zr1vUJ7QvBn42hPL","script":"","value":5000},{"id":"7TkKwDLyviM4yDBmkMxLHNYm2xUt1H5ut1wyPiKGggf5","script":"","value":5000},{"id":"8JMNET1RTfBjvYEZgANPH8qsq4ivewSobLjiqCVaweiv","script":"","value":10000},{"id":"3UihmFn7fmnLjsTeQ2RKXfsSiB6u2hph4ZfMxHn1QH37","script":"","value":10000}]}),AnyoneCanSpendTransaction({"id":"DiT83CKztDC9v5BRoa8ppzwFU8g87HpdFnPzmYWokFoT","inputs":[{"id":"4X4AwHT8JjEeQFYia3LHBYxHpwVUT7RvRRkma2XuShjh","nonce":4459653789108610744,"signature":""},{"id":"BybevS6TjgXJUWEtNjfG7UGR4zEgKo7crGcpysrSvfFK","nonce":-7250856857331732807,"signature":""},{"id":"FVvqxQGbxrt8ja19LTK9osr2sumugwrbCJphS9arqorr","nonce":1791091032912515863,"signature":""},{"id":"GDx5DkHLc6N8FFv9QMdecRkavHVGz66nUHG4ts1L2xWs","nonce":7433412003368471442,"signature":""},{"id":"Cca9w6qpU4QyQPYjPeKSJ3LePp1uc7asaTXmG5sHsPbo","nonce":-8015679778735875100,"signature":""}],"outputs":[{"id":"H2xSeW8D73wYBzm4PwYhHpDKxMjmJLnMnG7mSzgkADbF","script":"","value":5000},{"id":"Ga1FE2HgWQyUxEmqVpmb7Yo2aEfsWr6Tj8TLxFNVNf1m","script":"","value":5000},{"id":"545FoFmkbT7UHfGy1FSCTX1cqdAZMD1XKWFwCa7wE3JV","script":"","value":10000},{"id":"HEdib5RbKT4hZHUYU2HLoGq7B5Lx82u3DCKj7V5Pg8eT","script":"","value":10000},{"id":"VD62DJuU5PbYC7bXFM2dMadtedC56VrxshtTM8FVtpJ","script":"","value":10000},{"id":"5q1uA46mAh1GvPxooxnUTPrCPGuDVa3RpVPFntL3KZDT","script":"","value":5000}]}),AnyoneCanSpendTransaction({"id":"ASbqkQMC5yz6giY2XfkKHd19odAFmUUF2YxVZpAKmPor","inputs":[{"id":"9bfsKzvMLCCpB2ZLgFKYvQaqCALWLCmVNSeTrojBdkTv","nonce":-6799749748870816706,"signature":""},{"id":"88y8Fpb2XhBgLTiJTcHcuAm7vpmWoWeYamQjTdiVQZja","nonce":6331214036724070389,"signature":""},{"id":"88vJgjo6qLNfMrNsHmxT6v84MNmp9zTK9VvSzn7knEVr","nonce":-3806962394283529485,"signature":""},{"id":"ACkuaEs7yAAW8UxzfoMvZGv8nfFxKYcZ9PLFYgKrhZkB","nonce":-4425454035876161995,"signature":""},{"id":"GduiiMbsXAuMd5iZLVk2fJkuhLe7HEUxyAAFZajmB9xE","nonce":5463938781389291489,"signature":""},{"id":"AqyAaYikGGZfZPYNdgdb6586qc7Zt7eWLzrbH1rnpkPt","nonce":-1463050338226950891,"signature":""}],"outputs":[{"id":"6BXn4ybShSKs4iXKd65KxahgBHZtPqccxJQkEezFnbnB","script":"","value":2500},{"id":"5SLg8ipvLZ8Zuc4XcoMeB7pRzN4bwhYMm9EEra6PofRb","script":"","value":2500},{"id":"3685SQsdXkkEqppkS2Y3R71pzttzMQcwgiLd2VqW3hVe","script":"","value":5000},{"id":"9A7f13vZhbbr3rqLoi6iiPQ9cmo6fv6kQwKrXFuMneM4","script":"","value":10000},{"id":"6yM8zHK8wwrGp5ymSAjsrjgfUUoJSswQzGdYJ97rNyXK","script":"","value":10000},{"id":"5yKp9q9drfU6Cr955wLZkG5eFVTWbMan87xyZhAKP5T2","script":"","value":10000},{"id":"6AmVT9ncwanBuSZKZ1X1TaGYC4KhZLmkjDPexeXCwQsP","script":"","value":5000}]}),AnyoneCanSpendTransaction({"id":"2BS4RMpAr6hqjsvnCoZFxNh74Ud259sz3pWyW95QSk33","inputs":[{"id":"3nq4z7hwN8mPf3BQKdx1SCDK4DAPVPY1jMgRk5oy2EGU","nonce":-1936165366183984764,"signature":""},{"id":"EZG8vqq5gXFDxJEqLNowqXwYjtp85SvyUirqKG2SfKaZ","nonce":8190900862357295189,"signature":""},{"id":"7BSDJRFtpCajwzdNm7xzN2YmYjnSUGpkcqEezBQSbves","nonce":3313649365766822573,"signature":""},{"id":"4e48Hux4ve2EjsqEkEqCXBK52sxVtoLqmcsayZFqh6fV","nonce":-3003054614721717689,"signature":""},{"id":"4qzeXrqKwYEt3McxoLhUg7c1ZWjpdQdzLVQzDjg1ZUrC","nonce":6211332112520793235,"signature":""}],"outputs":[{"id":"8VHydaPKr25FNYKpHdn5GnquuwVS7zeqtts1V6Wf4wyZ","script":"","value":5000},{"id":"7LkgF4F7bV2y9pqVP4J83FtH9ryjTVWJRVo3SP2y4tn4","script":"","value":5000},{"id":"D4ngJ44d1yc12A9b8LkEnUxRtytDXFAdaCzVJzbMjFz9","script":"","value":10000},{"id":"3S1zy9jyFCfc3Yj1CnZ3j3dxgH7BKnoptPEk3pzocqZp","script":"","value":10000},{"id":"7yoS3P5Bqikygzm3qV8vwdaB1aTmUMDMKsh1kNYL8FWp","script":"","value":10000},{"id":"F1m4ddNW2cndeCXq5vFZoZmZKAHF6rsFSZktDpN8JNzs","script":"","value":5000}]}),AnyoneCanSpendTransaction({"id":"5LLkEuQAtojvFQZwQcBUNvmui5tHU1JwHfxTioAdwDbm","inputs":[{"id":"GXuqkumnR5aKCwc8fJA6zM7QBwbVtPXiADXgvAMGztGb","nonce":-6605400202729365588,"signature":""},{"id":"BeoFjbbXpKgfKwnus4mbTcESqNnCjF7RZhAoSvRD51wA","nonce":-4842304020044687585,"signature":""},{"id":"32M2Y2QGwoW1Y7nZuTKhz6mRmCSCWDZtmSeGbZZ1aDbA","nonce":4229222371131767029,"signature":""},{"id":"SeJnVMDtwbEDg5RdvPPTfp6RP8HVve7zXTtsEmM7XtY","nonce":-3390922140589033571,"signature":""},{"id":"Gn53HfWNvkFxKVBP2LF9j23oRypXSk1tqH6CHiNofB16","nonce":-8546001965517487941,"signature":""},{"id":"uBcb7X6WP4cEYc6mLUiRBJM5y3fidYqXGo6MDozPpGz","nonce":3147509249327840414,"signature":""},{"id":"CAMxVXkd6vLHGJ473x1BgoqkzaZANDMrzYQW4ojCiopB","nonce":1741256727538874006,"signature":""}],"outputs":[{"id":"F66MteeZ77Xw8hAZvsjveU7D6hGhP3gRHVY4dtNFWNsS","script":"","value":5000},{"id":"ErTgem6x3V1TFCF5jCnZDDarVyD5Ymd4khy2z2Wkn1vn","script":"","value":5000},{"id":"BcVbeEYP2QnEwreDm6Xdm8hn1GCNBoFEZq4h23ecTZuR","script":"","value":5000},{"id":"AMeLJbAsxNPYfMdHT6pNVNdYZSiamTn161ZN19AuSAZx","script":"","value":2500},{"id":"3ipPJ347LAmuMVgTVGzaXrMyuGDkK1PQkToggR8ZqEKf","script":"","value":10000},{"id":"CxrjUMEhLHg9xJWbzVY3H7U6wcVhXjm1KqCgeF2bjZnH","script":"","value":10000},{"id":"79qV1dygHdWT5yoqSgYDPwFPgihhYjGzfdsWRSrk15ry","script":"","value":10000},{"id":"6RfrNDHJQjT7bsUXuZzZdHGAwZ1qLKNqT17eam1MscTU","script":"","value":10000}]}),AnyoneCanSpendTransaction({"id":"7fUComnEVQ8M13s4tp7EqHVk8wfS7xWAh3UU9Psikd9p","inputs":[{"id":"ApngLQViEQLMNc93QkTdh9EevSg5mbap7UQHvenbBabE","nonce":-1121410605017711976,"signature":""}],"outputs":[{"id":"FQqkKyzfW3o8k85LaWJEn9tkqcq8F6icW1NtV9pr3jjD","script":"","value":5000},{"id":"GUvHGFFfAaiixPWj5GfSk1mxnvkMsEMBQLtMHd8WpsmA","script":"","value":5000}]}),AnyoneCanSpendTransaction({"id":"Ho8giDMycr6NkgJVSYySdrMo3C1WQ1NdjW7AxyHfzGgh","inputs":[{"id":"DSWbLy6m9qZcct1virupeLEVT7vhg2gDpVjVMjPgk3Wm","nonce":8208976548727221552,"signature":""},{"id":"EXymE6CDEWZ8pbd7UKmjNMydmg262KYnLSt3uYzxH93t","nonce":6860972170234684408,"signature":""},{"id":"4TkmVWQczyE6gPBkXhgnZRWPawCdhwueutyTS7xEP1yS","nonce":-6365494352230556519,"signature":""},{"id":"2juwCRbJmZyBGkRfJ9Tvn5Dxd9U1JdPwCyRT1YDM6Acn","nonce":-6539112507618886286,"signature":""},{"id":"ANz3SBrDeksVk5NJ9M2ZYKkP3SiVNF2nZLV57uroaUHG","nonce":-1342181916569245308,"signature":""}],"outputs":[{"id":"GWLXfA2BrwJ77nrEAhftsDaLicQz8rDq2ZghPuGtVMYQ","script":"","value":5000},{"id":"E6LHoAdRzm7P3XpxaiZEi2CMfeL9Fu1N6ftySWXe3BPR","script":"","value":5000},{"id":"EUjqqz3JCmtfNVYi2AAWfAxzrRJHoS8TSQfkho8Cw78M","script":"","value":10000},{"id":"JDrwv46KuNBFbVeRZpTK82Zadr6ecyV6LzwPyPCVimms","script":"","value":10000},{"id":"EpFvKjHrMAUpMQekwBsMRkXXkt8YNvASDF5s3esGkwmf","script":"","value":10000},{"id":"8inS2mJDMRpuKQAySFwDUb6EdPA1JgAzujtCpmtXaHh4","script":"","value":10000}]}), ...),Some(ADProofs(Id:AJYeqK59gTXXjjjDE1SYsewVzZogDsHT6zEfNTqZSnFj,HeaderId:51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3)))
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.nodeView.UtxoNodeViewHolder >> 19:38:59.062 Got locally generated modifier 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 of type 101
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.nodeView.UtxoNodeViewHolder >> 19:38:59.063 Apply modifier 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 of type 101 to nodeViewHolder
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.n.history.ErgoHistory$$anon$4 >> 19:38:59.063 New best header 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 with score 15. Hew height 14, old height 13
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.nodeView.UtxoNodeViewHolder >> 19:38:59.065 Got locally generated modifier D3BYG3wCJKY2mPUwP3tm5JvPq8dmZjoJHaDLhw7EGKPF of type 102
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.nodeView.UtxoNodeViewHolder >> 19:38:59.065 Apply modifier D3BYG3wCJKY2mPUwP3tm5JvPq8dmZjoJHaDLhw7EGKPF of type 102 to nodeViewHolder
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.n.history.ErgoHistory$$anon$4 >> 19:38:59.067 Full block 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 appended, going to apply 1 modifiers. New best block is 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 with height 14 updates block CEJPacawaSxMiBXcc7gzyqkbk4kqiwCLhEsPn4XGpxBU with height 13
[default-akka.actor.default-dispatcher-6] >> [INFO ] s.c.a.a.b.VersionedIODBAVLStorage >> 19:38:59.100 Update storage to version ByteArrayWrapper[0B1DB46E67D7D052A983B8208BDCFA0C77FFF650FE1D934B977DD609EF48220010]: 11290 elements to insert, 10723 elements to remove
[default-akka.actor.default-dispatcher-6] >> [WARN ] s.c.a.a.b.VersionedIODBAVLStorage >> 19:38:59.115 Failed to update tree
java.lang.IllegalArgumentException: duplicate key in `toUpdate`
	at io.iohk.iodb.LSMStore.$anonfun$update$3(LSMStore.scala:347)
	at io.iohk.iodb.LSMStore.$anonfun$update$3$adapted(LSMStore.scala:344)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at io.iohk.iodb.LSMStore.update(LSMStore.scala:344)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorage.$anonfun$update$1(VersionedIODBAVLStorage.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorage.update(VersionedIODBAVLStorage.scala:46)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.generateProofAndUpdateStorage(PersistentBatchAVLProver.scala:25)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:88)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:86)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:27)
	at scorex.core.NodeViewHolder.$anonfun$updateState$1(NodeViewHolder.scala:256)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scorex.core.NodeViewHolder.updateState(NodeViewHolder.scala:254)
	at scorex.core.NodeViewHolder.pmodModify(NodeViewHolder.scala:298)
	at scorex.core.NodeViewHolder.pmodModify$(NodeViewHolder.scala:284)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:23)
	at scorex.core.NodeViewHolder$$anonfun$processLocallyGeneratedModifiers$1.applyOrElse(NodeViewHolder.scala:385)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:23)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[default-akka.actor.default-dispatcher-6] >> [WARN ] o.e.nodeView.state.UtxoState >> 19:38:59.115 Error while applying full block with header 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 to UTXOState with root 2FbQ4SKXkru7YQ95CEDhU71YKEsfMATmdbUBY1T8wFXTdq: 
java.lang.IllegalArgumentException: duplicate key in `toUpdate`
	at io.iohk.iodb.LSMStore.$anonfun$update$3(LSMStore.scala:347)
	at io.iohk.iodb.LSMStore.$anonfun$update$3$adapted(LSMStore.scala:344)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at io.iohk.iodb.LSMStore.update(LSMStore.scala:344)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorage.$anonfun$update$1(VersionedIODBAVLStorage.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorage.update(VersionedIODBAVLStorage.scala:46)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.generateProofAndUpdateStorage(PersistentBatchAVLProver.scala:25)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:88)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:86)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:27)
	at scorex.core.NodeViewHolder.$anonfun$updateState$1(NodeViewHolder.scala:256)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scorex.core.NodeViewHolder.updateState(NodeViewHolder.scala:254)
	at scorex.core.NodeViewHolder.pmodModify(NodeViewHolder.scala:298)
	at scorex.core.NodeViewHolder.pmodModify$(NodeViewHolder.scala:284)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:23)
	at scorex.core.NodeViewHolder$$anonfun$processLocallyGeneratedModifiers$1.applyOrElse(NodeViewHolder.scala:385)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:23)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.n.history.ErgoHistory$$anon$4 >> 19:38:59.161 Going to invalidate 51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3 and List(51Tp5uaezfrwieqfkNz145uPfm5CSV68PrCtXkdRYps3)
[default-akka.actor.default-dispatcher-6] >> [INFO ] o.e.nodeView.UtxoNodeViewHolder >> 19:38:59.185 Persistent modifier D3BYG3wCJKY2mPUwP3tm5JvPq8dmZjoJHaDLhw7EGKPF applied successfully
```

**Comment by catena2w** [comment]
fixed in https://github.com/input-output-hk/scrypto/pull/39
