### ISSUE TITLE
Calculated proofHash is not equal to the declared one

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#289]
Attempt to state racalculation leads to error
```
[ergoref-akka.actor.default-dispatcher-2] >> [WARN ] o.e.nodeView.state.UtxoState >> 19:30:27.574 Error while applying full block with header 8bFstSivcfbGyky1XGR5qbvNTs8YZgZJkbDxbVxhtA4 to UTXOState with root d3Ezjcs4JU8yEjGTaA1QC744YemBbE1Cpu5TjfKT93VVy:
java.lang.Error: Calculated proofHash is not equal to the declared one
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:96)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:86)

```

**Comment by catena2w** [comment]
clone of https://github.com/ergoplatform/ergo/issues/309
