### ISSUE TITLE
mining nodes failures

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#303]
Mining nodes on testnet stucked with 3 errors like:
```
[ergoref-akka.actor.default-dispatcher-87948] >> [WARN ] o.e.nodeView.state.UtxoState >> 16:26:59.808 Error while applying full block with header 001d23d6f79c69e8ead84f0b1d28d41d4f6b7d76f2be
b1cdc493c75ffb33ce04 to UTXOState with root 6e767fe9d27f153d97e4443a8dd0b38432644b9d184d9862569cc48a35eaa51a0f: 
java.lang.Error: Box with id c131dcef9acb0a01a3d9b4add7263906de4dba183ec215545451c901c0d80693 not found
        at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyTransactions$6(UtxoState.scala:77)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyTransactions$4(UtxoState.scala:74)
```

Resulting to 
```
[ergoref-akka.actor.default-dispatcher-88434] >> [WARN ] o.e.nodeView.state.UtxoState >> 16:27:21.135 Closing state's store.
java.lang.IllegalArgumentException: versionID is already used
        at io.iohk.iodb.LSMStore.update(LSMStore.scala:354)
        at org.ergoplatform.nodeView.history.storage.HistoryStorage.insert(HistoryStorage.scala:37)
        at org.ergoplatform.nodeView.history.ErgoHistory.reportModifierIsInvalid(ErgoHistory.scala:151)
        at org.ergoplatform.nodeView.history.ErgoHistory.reportModifierIsInvalid$(ErgoHistory.scala:105)
        at org.ergoplatform.nodeView.history.ErgoHistory$$anon$4.reportModifierIsInvalid(ErgoHistory.scala:233)
        at org.ergoplatform.nodeView.history.ErgoHistory$$anon$4.reportModifierIsInvalid(ErgoHistory.scala:233)
        at scorex.core.NodeViewHolder.$anonfun$updateState$1(NodeViewHolder.scala:257)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at scorex.core.NodeViewHolder.updateState(NodeViewHolder.scala:248)
        at scorex.core.NodeViewHolder.pmodModify(NodeViewHolder.scala:295)
        at scorex.core.NodeViewHolder.pmodModify$(NodeViewHolder.scala:281)
        at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:23)
        at scorex.core.NodeViewHolder$$anonfun$processRemoteModifiers$1.$anonfun$applyOrElse$9(NodeViewHolder.scala:370)
```

**Comment by catena2w** [comment]
Header was marked invalid, but full block was processing 2 times (and 1 time different full block at the same height)
