### ISSUE TITLE
Proof creation at a time of block application

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#409]
When our node is mining, it may create proofs for block transactions at the same time, as another block being applied. This leads to incorrect local block generation and node crash

**Comment by catena2w** [comment]
Typical log:
```
21:27:44.825 INFO  [ctor.default-dispatcher-9] o.e.n.state.UtxoState - Valid modifier with header 009fc39647ffed634b7ca440e4a8229bd46d8332db9a41c5c71626fec42a6ebb and emission box Some(f8d2a
7de6b3a465f504d805d45ce5a28997da6bf1c6cbd25ce2129e32539cada) applied to UtxoState with root hash e5291029e1f84d05ed2832ba8fa9bcc2e30e9942a2af1cad2990639cb7bf9d6417
21:27:44.825 DEBUG [ctor.default-dispatcher-9] o.e.n.h.ErgoHistory$$anon$2 - Modifier 009fc39647ffed634b7ca440e4a8229bd46d8332db9a41c5c71626fec42a6ebb of type -127 is marked as valid 
21:27:44.894 DEBUG [ctor.default-dispatcher-9] o.e.n.state.UtxoState - Trying to apply full block with header 007a072feb504aeb1acc8abebe59974448188464626b832dc4b9a05bb71c7183 at height 33447
21:27:44.894 INFO  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to Ubuntu-1710-artful-64-minimal/78.46.93.239:55338
21:27:44.895 INFO  [.default-dispatcher-12132] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to 209.97.136.204/209.97.136.204:9003
21:27:44.895 INFO  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to 209.97.134.210/209.97.134.210:9003
21:27:44.895 INFO  [.default-dispatcher-12132] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to static.88-198-13-202.clients.your-server.de/88.198.13.202:9003
21:27:44.896 INFO  [r.default-dispatcher-4869] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to Ubuntu-1710-artful-64-minimal/78.46.93.239:55338
21:27:44.896 INFO  [r.default-dispatcher-4869] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to 209.97.136.204/209.97.136.204:9003
21:27:44.896 INFO  [ctor.default-dispatcher-4] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to 209.97.134.210/209.97.134.210:9003
21:27:44.897 INFO  [r.default-dispatcher-4869] s.c.n.PeerConnectionHandler - Send message MessageSpec(55: Inv) to static.88-198-13-202.clients.your-server.de/88.198.13.202:9003
21:27:44.900 DEBUG [r.default-dispatcher-4868] o.e.n.state.UtxoState - Going to create proof for 8 transactions at root 943aa0fb647b6069afe0125ea84381fe2392287f43a72c6ccee2ea4a383d9c0017
21:27:44.902 WARN  [r.default-dispatcher-4868] o.e.local.ErgoMiner - Failed to produce candidate block.
java.lang.Exception: Key 37d122cf2008926a3b8e47fe4c988049a4640b3e195eab248ce5db27dc70c521 does not exist
....
21:27:44.909 WARN  [ctor.default-dispatcher-9] o.e.n.state.UtxoState - Error while applying full block with header 007a072feb504aeb1acc8abebe59974448188464626b832dc4b9a05bb71c7183 to UTXOState with root 943aa0fb647b6069afe0125ea84381fe2392287f43a72c6ccee2ea4a383d9c0017: 
java.lang.Error: Digest after txs application is wrong. c121102308bb6ccf13b94d9a6ed2b0a03893aa798731e314c2bcabb619442d7d17 expected, 6f21dc246f0e72b1bdfb22cb7370567a4be91d56ef48ec2d0a549da76334c0ca17 given
        at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyTransactions$1(UtxoState.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.Try$.apply(Try.scala:209)
        at org.ergoplatform.nodeView.state.UtxoState.applyTransactions(UtxoState.scala:69)
        at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:105)
        at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:30)
...
21:28:55.631 DEBUG [ctor.default-dispatcher-9] o.e.n.h.ErgoHistory$$anon$2 - Modifier 007a072feb504aeb1acc8abebe59974448188464626b832dc4b9a05bb71c7183 of type -127 is marked as invalid


```
