### ISSUE TITLE
Exception when starting node

### ISSUE THREAD

**Issue by Zud71** [ergoplatform/ergo#832]
```
[ERROR] [07/05/2019 10:53:06.969] [ergoref-akka.actor.default-dispatcher-6] [akka://ergoref/user/$b] assertion failed
akka.actor.ActorInitializationException: akka://ergoref/user/$b: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:202)
        at akka.actor.ActorCell.create(ActorCell.scala:696)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at akka.util.Reflect$.instantiate(Reflect.scala:68)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:648)
        at akka.actor.ActorCell.create(ActorCell.scala:674)
        ... 9 more
Caused by: java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:208)
        at scala.Predef$Ensuring$.ensuring$extension2(Predef.scala:320)
        at org.ergoplatform.nodeView.state.ErgoState$.generateGenesisUtxoState(ErgoState.scala:196)
        at org.ergoplatform.nodeView.state.ErgoState$.readOrGenerate(ErgoState.scala:219)
        at org.ergoplatform.nodeView.ErgoNodeViewHolder.recreatedState(ErgoNodeViewHolder.scala:125)
        at org.ergoplatform.nodeView.ErgoNodeViewHolder.genesisState(ErgoNodeViewHolder.scala:88)
        at scorex.core.NodeViewHolder.$anonfun$nodeView$1(NodeViewHolder.scala:62)
        at scala.Option.getOrElse(Option.scala:138)
        at scorex.core.NodeViewHolder.$init$(NodeViewHolder.scala:62)
        at org.ergoplatform.nodeView.ErgoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:25)
        at org.ergoplatform.nodeView.UtxoNodeViewHolder.<init>(ErgoNodeViewHolder.scala:220)
        ... 19 more
```

**Comment by oskin1** [comment]
Seems you use incorrect genesis settings. This is why actual state digest mismatches the one declared in the config.
