### ISSUE TITLE
Node can not restore after long network degradation (restart helps)

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/ergo#894]
After long (approx. 2 hours) network degradation, node can not back to normal work. Logs are:

Logs:

```
00:17:41.097 WARN  [tor.default-dispatcher-34] s.c.u.NetworkTimeProvider - Problems with NTP: 
java.net.SocketTimeoutException: Receive timed out
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
	at java.base/java.net.DatagramSocket.receive(Unknown Source)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:91)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:113)
	at scorex.core.utils.NetworkTimeProvider.$anonfun$updateOffset$1(NetworkTime.scala:34)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
00:18:21.097 WARN  [tor.default-dispatcher-34] s.c.u.NetworkTimeProvider - Problems with NTP: 
java.net.SocketTimeoutException: Receive timed out
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
	at java.base/java.net.DatagramSocket.receive(Unknown Source)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:91)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:113)
	at scorex.core.utils.NetworkTimeProvider.$anonfun$updateOffset$1(NetworkTime.scala:34)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
00:19:01.172 WARN  [tor.default-dispatcher-34] s.c.u.NetworkTimeProvider - Problems with NTP: 
java.net.SocketTimeoutException: Receive timed out
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
	at java.base/java.net.DatagramSocket.receive(Unknown Source)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:91)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:113)
	at scorex.core.utils.NetworkTimeProvider.$anonfun$updateOffset$1(NetworkTime.scala:34)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
00:19:11.092 INFO  [tor.default-dispatcher-35] s.c.u.NetworkTimeProvider - New offset adjusted: -3
00:49:11.457 INFO  [tor.default-dispatcher-35] s.c.u.NetworkTimeProvider - New offset adjusted: 0
01:19:11.753 INFO  [tor.default-dispatcher-39] s.c.u.NetworkTimeProvider - New offset adjusted: 1
01:49:12.901 INFO  [tor.default-dispatcher-36] s.c.u.NetworkTimeProvider - New offset adjusted: 19
02:19:13.721 INFO  [tor.default-dispatcher-37] s.c.u.NetworkTimeProvider - New offset adjusted: -1
02:49:14.365 INFO  [tor.default-dispatcher-32] s.c.u.NetworkTimeProvider - New offset adjusted: -1
03:19:15.212 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 0
03:49:15.561 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 0
04:19:15.960 INFO  [tor.default-dispatcher-32] s.c.u.NetworkTimeProvider - New offset adjusted: 2
04:49:16.673 INFO  [tor.default-dispatcher-40] s.c.u.NetworkTimeProvider - New offset adjusted: 9
05:19:17.421 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 6
05:49:18.156 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 5
06:19:19.178 INFO  [tor.default-dispatcher-42] s.c.u.NetworkTimeProvider - New offset adjusted: 3
06:49:19.255 INFO  [tor.default-dispatcher-34] s.c.u.NetworkTimeProvider - New offset adjusted: 32
07:19:20.111 INFO  [tor.default-dispatcher-42] s.c.u.NetworkTimeProvider - New offset adjusted: 3
07:49:20.805 INFO  [tor.default-dispatcher-34] s.c.u.NetworkTimeProvider - New offset adjusted: 5
08:19:21.619 INFO  [tor.default-dispatcher-42] s.c.u.NetworkTimeProvider - New offset adjusted: 6
08:49:22.378 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 4
09:19:22.630 INFO  [tor.default-dispatcher-39] s.c.u.NetworkTimeProvider - New offset adjusted: 2
09:49:22.704 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 4
10:19:22.865 INFO  [tor.default-dispatcher-41] s.c.u.NetworkTimeProvider - New offset adjusted: 3
10:49:23.614 INFO  [tor.default-dispatcher-40] s.c.u.NetworkTimeProvider - New offset adjusted: 5
11:19:24.452 INFO  [tor.default-dispatcher-40] s.c.u.NetworkTimeProvider - New offset adjusted: 4
```

Grafana looks like:

![image](https://user-images.githubusercontent.com/758910/63937037-2b1a5180-ca6a-11e9-8157-a74c8f124948.png)

Peers count graph:

![image](https://user-images.githubusercontent.com/758910/63937719-b21bf980-ca6b-11e9-99df-314f0353ca3d.png)

As we can see, at 2:28 network is down, restored at 3:24, and node can not do nothing until reboot at 14:20

**Comment by kushti** [comment]
Fixed in 3.3.5 ( #1225 )
